jobs:
  e2e_test:
    name: e2e_test ${{ matrix.specs.group }}
    needs: prepare_e2e_test_matrix
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up secrets
      run: 'echo "CYPRESS_RECORD_KEY=$(echo YzE3ZDU4OGItZTBkOC00ZjJmLTg4NjYtNzJmNmFmYmRhNGQxCg==
        | base64 -d)" >> $GITHUB_ENV

        echo "CYPRESS_PROJECT_ID=s5du3k" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build OpenRefine
      run: ./refine build
    - continue-on-error: true
      name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - continue-on-error: true
      name: Restore Tests dependency cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        path: '~/cache

          ~/.cache

          **/node_modules

          !~/cache/exclude

          '
        restore-keys: '${{ runner.os }}-yarn

          '
    - continue-on-error: true
      name: Install test dependencies
      run: 'cd ./main/tests/cypress

        npm i -g yarn

        yarn install

        '
    - continue-on-error: true
      env:
        CYPRESS_BROWSER: ${{ matrix.browser }}
        CYPRESS_CI_BUILD_ID: ${{ github.run_id }}
        CYPRESS_GROUP: ${{ matrix.specs.group }}
        CYPRESS_PROJECT_ID: ${{ env.CYPRESS_PROJECT_ID }}
        CYPRESS_RECORD_KEY: ${{ env.CYPRESS_RECORD_KEY }}
        CYPRESS_SPECS: ${{ matrix.specs.paths }}
      name: Test with Cypress on ${{ matrix.browser }}
      run: 'echo REFINE_MIN_MEMORY=1400M >> ./refine.ini

        echo REFINE_MEMORY=4096M >> ./refine.ini

        ./refine e2e_tests

        '
    strategy:
      matrix: ${{fromJSON(needs.prepare_e2e_test_matrix.outputs.matrix)}}
  prepare_e2e_test_matrix:
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - continue-on-error: true
      env:
        browsers: chrome
      id: set-matrix
      run: npm install --save glob@8.1.0 && node main/tests/cypress/build-test-matrix.js
        >> $GITHUB_OUTPUT
name: CI
on:
  repository_dispatch:
    types: trigger-ga___pull_request_e2e.yml
permissions: read-all
