jobs:
  unassign-good-first-issues-after-90-days-of-inactivity:
    if: github.repository == 'OpenRefine/OpenRefine'
    name: Unassign issues labeled "good first issue" after 45 days of inactivity.
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: boundfoxstudios/action-unassign-contributor-after-days-of-inactivity@v1.0.3
      with:
        exempt-assignees: ''
        labels: good first issue
        labels-to-remove: ''
        last-activity: 45
        message: Automatically unassigned after 45 days of inactivity.
name: Unassign contributors from issues after a delay
on:
  repository_dispatch:
    types: trigger-ga___unassign_issues.yml
